# typos configuration file

# Do not check spelling in these files
[files]
ignore-files = [
  "*.sum",
  "go.sum",
  "*.trpc.go",
  "*.pb.go",
  "*_string.go",
  "*.gen.go"
]

[default.extend-identifiers]
# TODO = "TODO" 