run:
  timeout: 5m
  skip-dirs:
    - vendor
  skip-files:
    - ".*\\\.pb\\.go$"
    - ".*\\\.trpc\\.go$"

linters:
  enable:
    - bodyclose
    - dogsled
    - durationcheck
    - errcheck
    - exportloopref
    - goconst
    - gocritic
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck # don't check errors in tests 